# Generated by Django 5.2.6 on 2025-11-11 16:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('zona', models.CharField(blank=True, max_length=50)),
                ('populacao', models.IntegerField(blank=True, null=True)),
                ('area_km2', models.FloatField(blank=True, null=True)),
                ('risco_base', models.IntegerField(default=1, help_text='Nível base de risco do bairro (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'db_table': 'bairros',
            },
        ),
        migrations.CreateModel(
            name='EstatisticaDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('hora_referencia', models.IntegerField(blank=True, null=True)),
                ('total_relatos', models.IntegerField(default=0)),
                ('relatos_criticos', models.IntegerField(default=0)),
                ('relatos_altos', models.IntegerField(default=0)),
                ('relatos_moderados', models.IntegerField(default=0)),
                ('relatos_baixos', models.IntegerField(default=0)),
                ('total_confirmacoes', models.IntegerField(default=0)),
                ('usuarios_ativos', models.IntegerField(default=0)),
                ('taxa_confirmacao_media', models.FloatField(default=0.0)),
                ('bairro_mais_afetado', models.CharField(blank=True, max_length=100)),
                ('severidade_media_dia', models.FloatField(default=0.0)),
                ('timestamp_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estatística do Dashboard',
                'verbose_name_plural': 'Estatísticas do Dashboard',
                'db_table': 'estatisticas_dashboard',
                'indexes': [models.Index(fields=['data_referencia'], name='estatistica_data_re_31cc8f_idx'), models.Index(fields=['timestamp_calculo'], name='estatistica_timesta_91ae88_idx')],
                'unique_together': {('data_referencia', 'hora_referencia')},
            },
        ),
        migrations.CreateModel(
            name='RelatorioAlagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_relato', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('endereco_aproximado', models.CharField(blank=True, max_length=200)),
                ('nivel_severidade', models.IntegerField(choices=[(1, "🟢 Baixo - Poças d'água"), (2, '🟡 Moderado - Alagamento leve'), (3, '🟠 Alto - Alagamento significativo'), (4, '🔴 Crítico - Alagamento severo')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('descricao', models.TextField(blank=True, max_length=500)),
                ('altura_agua_cm', models.IntegerField(blank=True, help_text='Altura em centímetros', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='relatos/')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('resolvido', 'Resolvido'), ('falso_positivo', 'Falso Positivo'), ('spam', 'Spam')], default='ativo', max_length=20)),
                ('total_confirmacoes', models.IntegerField(default=0)),
                ('total_negacoes', models.IntegerField(default=0)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('confiabilidade_ml', models.FloatField(default=0.5, help_text='Score de confiabilidade do ML')),
                ('validado_automaticamente', models.BooleanField(default=False)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.bairro')),
            ],
            options={
                'verbose_name': 'Relatório de Alagamento',
                'verbose_name_plural': 'Relatórios de Alagamento',
                'db_table': 'relatorios_alagamento',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_alerta', models.IntegerField(choices=[(1, 'Baixo'), (2, 'Moderado'), (3, 'Alto'), (4, 'Crítico')])),
                ('total_relatos_ativos', models.IntegerField()),
                ('severidade_media', models.FloatField()),
                ('raio_afetado_metros', models.IntegerField(default=500)),
                ('timestamp_criacao', models.DateTimeField(auto_now_add=True)),
                ('timestamp_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.bairro')),
                ('relatos_origem', models.ManyToManyField(related_name='alertas_gerados', to='dashboard.relatorioalagamento')),
            ],
            options={
                'verbose_name': 'Alerta de Área',
                'verbose_name_plural': 'Alertas de Área',
                'db_table': 'alertas_area',
                'ordering': ['-nivel_alerta', '-timestamp_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(default='Usuário Anônimo', max_length=50)),
                ('pontos_contribuicao', models.IntegerField(default=0)),
                ('nivel_confiabilidade', models.FloatField(default=0.5)),
                ('total_relatos', models.IntegerField(default=0)),
                ('relatos_validados', models.IntegerField(default=0)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário do App',
                'verbose_name_plural': 'Usuários do App',
                'db_table': 'usuarios_app',
            },
        ),
        migrations.AddField(
            model_name='relatorioalagamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatos', to='dashboard.usuarioapp'),
        ),
        migrations.CreateModel(
            name='InteracaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacao', 'Confirmação'), ('negacao', 'Negação'), ('comentario', 'Comentário'), ('atualizacao', 'Atualização de Status')], max_length=20)),
                ('comentario', models.TextField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('relevante', models.BooleanField(default=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='dashboard.relatorioalagamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuarioapp')),
            ],
            options={
                'verbose_name': 'Interação com Relatório',
                'verbose_name_plural': 'Interações com Relatórios',
                'db_table': 'interacoes_relatorio',
            },
        ),
        migrations.AddIndex(
            model_name='relatorioalagamento',
            index=models.Index(fields=['bairro', 'nivel_severidade'], name='relatorios__bairro__085e12_idx'),
        ),
        migrations.AddIndex(
            model_name='relatorioalagamento',
            index=models.Index(fields=['timestamp'], name='relatorios__timesta_0c9a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='relatorioalagamento',
            index=models.Index(fields=['status'], name='relatorios__status_1e1aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='interacaorelatorio',
            index=models.Index(fields=['relatorio', 'tipo'], name='interacoes__relator_86adbc_idx'),
        ),
        migrations.AddIndex(
            model_name='interacaorelatorio',
            index=models.Index(fields=['timestamp'], name='interacoes__timesta_c69f23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interacaorelatorio',
            unique_together={('relatorio', 'usuario', 'tipo')},
        ),
    ]
