# Generated by Django 5.2.6 on 2025-11-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.CharField(default='Recife', max_length=100),
        ),
        migrations.AddField(
            model_name='bairro',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bairro',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bairro',
            name='uf',
            field=models.CharField(default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='bairro',
            unique_together={('nome', 'cidade', 'uf')},
        ),
    ]
